---
layout: post
title: 예외처리(Exception)
categories: Java
tags: [Java]
---
- 구현된 프로그램 로직에서 발생하는 오류를 의미
- 발생하는 Exception을 적절하게 처리해야 프로그램이 종료되지 않고 원활히 돌아가게 할 수 있다

- `Exception` VS `Error`
  - `Exception`(예외) : 구현한 로직에서 발생. 처리가능
  - `Error`(에러) : 시스템레벨에서 발생. 처리불가능 

## Exception 종류
![image](https://user-images.githubusercontent.com/48157259/168767264-a6e1e9ce-f107-4387-b2a1-f22f766edcab.png)

### 1. Checked Exception
- 컴파일시 체크되는 exception
- 반드시 예외처리가 되어야한다  
ex) `ClassNotFoundException`


### 2. Unchecked Exception
- 컴파일시 체크되지 않고 런타임시 발생하는 exception
- `RuntimeException`을 상속하는 exception
- 예외처리를 하지 않아도 프로그램은 돌아간다  
ex) `NullPointerException`


## Exception 처리
### 1. try-catch-finally (복구)
- 현재 로직에서 예외를 처리하는 방법
- try-catch 문에서 여러개를 catch할 경우, 하위에 해당하는 Exception부터 처리해야 한다  
  - ArithmeticException -> RuntimeException -> Exception 순

```java
public class ExceptionEx1 {

	public static void main(String[] args) {
		try {
		    System.out.println(1/0);
		} catch (ArithmeticException e) {		//ArithmeticException만 실행
		    System.out.println("0으로 나누지 마세요");
        	e.printStackTrace();
		} catch (RuntimeException e) {			//RuntimeException중 ArithmeticException이 아닌것만 실행
		    System.out.println("연락요망");
		    e.printStackTrace();	
		} catch (Exception e) {				 //RuntimeException 이외의 나머지 Exception이 실행		
       		 e.printStackTrace();
        }
    }

}
```
- try문을 실행하다가 예외가 발생했을 때 여러개의 catch문이 존재한다면 위에서부터 instanceof의 결과가 true인 catch문을 찾아내려간다. 찾으면 그 catch문 하나만을 실행하고 try-catch문을 빠져나온다


- `finally` 구문은 예외가 발생하던 발생하지 않던 무조건 마지막에 실행된다 
  - 자원 해제 등을 위해 사용한다

```java
public class ExceptionEx2 {

	public static void main(String[] args) {
		try {
			System.out.print(1);
			System.out.print(2);
			System.out.print(3/0);		// exception 발생
			System.out.print(4);
		} catch (Exception e) {
			System.out.print(5);
			return;				 //main method 종료
		} finally {
			System.out.print(6);
		}
		System.out.print(7);
	}	
}

```

```java
> 1256
```

### 2. try-with-resource (복구)
- 자바 7버전부터 추가된 문법
- finally를 사용해서 자원을 수동으로 해제시켜줘야 했지만 이 문법을 사용하면 try구문이 끝나면 자동으로 자원을 해제시켜준다
- try절 시작시 할당한 자원을 구문종료시 해제시킨다

```java

```

### 3. throws (회피)
- 현재 로직에서 exception이 발생해도 처리하지 않고 자신을 호출한 상위 메서드로 던지는 방법 (책임회피)
- 상위 메서드에 던지지만 처리되지 않고 메인메서드까지 던져진다면 에러는 처리되지 않게 된다

```java
public void doSomething() throws Exception { 
	//something
}
```

#### throw 키워드
 - Exception을 발생시키는 키워드

```java
public class ThrowEx {
	public static void main(String[] args) {
		try {
		    Exception e = new Exception("고의로 발생");
		    throw e;				// = throw new Exception("고의로 발생");
		} catch (Exception e) {
		    e.printStackTrace();
		    System.out.println(e.getMessage());
		}
	}
}
```

```
> java.lang.Exception: 고의로 발생
  	at ch08.ThrowEx.main(asdf.java:7)
  고의로 발생
```

### 4. 예외 전환
- 발생한 예외에 대해 또 다른 예외로 변경하는 것
- 특정한 Exception이 발생하면 새로운 Exception으로 전환하여 구체적으로 예외를 다룰 수 있다
- `CheckedException`을 `UncheckedException`으로 전환하여 예외를 다룰 수 있도록 전환이 가능하다
- 예외를 전환할 경우 Cause 예외를 담아서 던져야 한다
  - 발생한 예외를 전환시킬 예외의 생성자로 넘겨줘야 정보가 사라지지 않고 상위로 전달된다

```java
try {
	...
} catch (xxxException e) {
	throw CustomxxxxxException(e);
}
```

## 예외처리하는 방법
1\. `catch`문에는 로깅과 복구로직을 추가해라
- 로그를 찍을 때는 `e.printStackTrace()`를 사용하지 말고 로그 프레임워크를 사용

2\. Exception을 무시하거나 다시 던지지 마라

3\. 리소스 정리
- 리소스를 사용하는 구문이라면 반드시 리소스를 해제해야 한다

4\. 더 자세한 예외
- 메서드 정의시 발생하는 예외를 최대한 자세한 예외를 명세하는 것이 좋습니다

```java
// bad
public void exceptableMethod() throw Exception;

// good
public void execptableMethod() throw NumberFormatException;
```

5\. 메시지를 자세하게 적는다
- 예외가 발생하면 메시지를 보고 처리할 수 있도록 가능한 자세하게 적어야 한다


<hr>

\<참고자료>  
https://soft.plusblog.co.kr/160